# Perfil de Produção
spring:
  # --- Event Store: PostgreSQL Database ---
  jpa:
    hibernate:
      ddl-auto: validate # Em produção real, use um gerenciador de migração como Flyway/Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/event_store # Conecta-se ao container 'postgres'
    username: 'admin'
    password: 'admin'
    driver-class-name: org.postgresql.Driver
  # --- Read Model: Elasticsearch ---
  elasticsearch:
    uris: http://elasticsearch:9200 # Conecta-se ao container 'elasticsearch'