# application.yml
server:
  port: 8081

spring:
  application:
    name: stockeventsourcing
  profiles:
    active: dev # Perfil padrão para facilitar a execução local via IDE
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    com.juhmaran.stockeventsourcing: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: ALWAYS
